import { useEffect, useMemo, useState } from 'react'
import { Edit3, Plus, Trash2 } from 'lucide-react'
import { motion } from 'framer-motion'
import api, { getError } from '../services/api'
import { Badge, Button, Card, Empty, Input, Modal, SearchBox, Select, Textarea, Toast } from '../components/ui'
import { useAuth } from '../context/AuthContext'
import { resources } from './resources'

const tone=v=>['active','present','completed'].includes(v)?'green':['inactive','absent','cancelled','dropped'].includes(v)?'red':['pending','late','upcoming','pending_approval'].includes(v)?'yellow':'blue'
const display=v=>{if(v===null||v===undefined||v==='')return '—';if(typeof v==='object'){if(Array.isArray(v))return v.map(display).join(', ');if(v.name)return v.name;if(v.firstName)return `${v.firstName} ${v.lastName||''}`.trim();if(v.code)return v.code;return v._id?.slice(-8)||'—'}return String(v)}
const idOf=v=>typeof v==='object'?v?._id||'':v||''
const dateInput=v=>v?String(v).slice(0,10):''

function Field({field,value,onChange,options}){
  const [name,label,type,required,extra]=field
  if(type==='textarea') return <div className="sm:col-span-2"><Textarea label={label} required={required} value={value??''} onChange={e=>onChange(e.target.value)}/></div>
  if(type==='select') return <Select label={label} required={required} value={value??''} onChange={e=>onChange(e.target.value)}><option value="">Select…</option>{extra.map(x=><option key={x} value={x}>{x}</option>)}</Select>
  if(type==='relation') return <Select label={label} required={required} value={idOf(value)} onChange={e=>onChange(e.target.value)}><option value="">Select…</option>{(options[extra]||[]).map(x=><option key={x._id} value={x._id}>{display(x)}</option>)}</Select>
  if(type==='multiselect') return <Select label={label} multiple value={Array.isArray(value)?value.map(idOf):[]} onChange={e=>onChange([...e.target.selectedOptions].map(x=>x.value))} className="min-h-28">{(options[extra]||[]).map(x=><option key={x._id} value={x._id}>{display(x)}</option>)}</Select>
  if(type==='checkbox') return <label className="flex items-center gap-3 pt-7 text-sm font-medium text-slate-700"><input type="checkbox" checked={Boolean(value)} onChange={e=>onChange(e.target.checked)} className="size-4 rounded"/>{label}</label>
  return <Input label={label} type={type} required={required} value={type==='date'?dateInput(value):value??''} onChange={e=>onChange(type==='number'?(e.target.value===''?'':Number(e.target.value)):e.target.value)}/>
}

export default function CrudPage({config}){
  const {user}=useAuth(); const [rows,setRows]=useState([]); const [options,setOptions]=useState({}); const [loading,setLoading]=useState(true); const [q,setQ]=useState(''); const [open,setOpen]=useState(false); const [editing,setEditing]=useState(null); const [form,setForm]=useState({}); const [error,setError]=useState(''); const [toast,setToast]=useState('')
  const canWrite=config.write.includes(user.role), canDelete=config.delete.includes(user.role)
  const load=async()=>{setLoading(true);try{const r=await api.get(config.endpoint,{params:config.search&&q?{q}:undefined});setRows(r.data[config.key]||[])}catch(e){setError(getError(e))}finally{setLoading(false)}}
  useEffect(()=>{load()},[q,config.endpoint])
  useEffect(()=>{let cancelled=false;(async()=>{const names=[...new Set(config.fields.map(f=>f[4]).filter(x=>typeof x==='string'&&resources[x]))];const out={};await Promise.all(names.map(async name=>{try{const c=resources[name];const r=await api.get(c.endpoint);out[name]=r.data[c.key]||[]}catch{out[name]=[]}}));if(!cancelled)setOptions(out)})();return()=>{cancelled=true}},[config])
  const columns=useMemo(()=>config.columns,[config.columns])
  const openCreate=()=>{const o={};config.fields.forEach(f=>o[f[0]]=f[2]==='multiselect'?[]:f[2]==='checkbox'?false:'');setForm(o);setEditing(null);setOpen(true)}
  const openEdit=r=>{const o={};config.fields.forEach(f=>{const v=r[f[0]];o[f[0]]=f[2]==='date'?dateInput(v):f[2]==='multiselect'?(Array.isArray(v)?v.map(idOf):[]):f[2]==='checkbox'?Boolean(v):idOf(v)});setForm(o);setEditing(r);setOpen(true)}
  const save=async e=>{e.preventDefault();setError('');const body={};for(const f of config.fields){const [name,,type]=f;const v=form[name];if(v!==''&&v!==null&&v!==undefined)body[name]=v;if(type==='multiselect'&&Array.isArray(v))body[name]=v}try{const response=editing?await api.patch(`${config.endpoint}/${editing._id}`,body):await api.post(config.endpoint,body);setOpen(false);const count=response.data?.sessions?.length;if(config.endpoint==='/batches'&&count!==undefined){setToast(`${editing?'Updated':'Created'} batch · ${count} class session${count===1?'':'s'} synced${response.data?.warnings?.length?' · Zoom needs attention':''}`)}else{setToast(editing?'Updated successfully':'Created successfully')}load()}catch(e){setError(getError(e))}}
  const remove=async id=>{if(!window.confirm('Delete this record?'))return;try{await api.delete(`${config.endpoint}/${id}`);setToast('Deleted successfully');load()}catch(e){setError(getError(e))}}
  return <div className="space-y-5"><Toast message={toast} onClose={()=>setToast('')}/><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-semibold text-indigo-600">Management</p><h1 className="mt-1 text-2xl font-black text-slate-900">{config.title}</h1><p className="mt-1 text-sm text-slate-500">Live data from {config.endpoint}.</p></div>{canWrite&&<Button onClick={openCreate}><Plus size={17}/>Add {config.singular}</Button>}</div>{error&&<Card className="p-4 text-sm text-rose-600">{error}</Card>}<Card className="overflow-hidden"><div className="border-b border-slate-100 p-4">{config.search&&<div className="max-w-sm"><SearchBox value={q} onChange={setQ}/></div>}</div><div className="overflow-x-auto">{loading?<div className="p-10 text-center text-sm text-slate-400">Loading…</div>:rows.length===0?<Empty/>:<table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-400"><tr>{columns.map(name=><th key={name} className="px-5 py-3 font-semibold">{config.fields.find(f=>f[0]===name)?.[1]||name}</th>)}{(canWrite||canDelete)&&<th className="px-5 py-3">Actions</th>}</tr></thead><tbody className="divide-y divide-slate-100">{rows.map((r,i)=><motion.tr initial={{opacity:0}} animate={{opacity:1}} transition={{delay:i*.02}} key={r._id} className="hover:bg-slate-50/70">{columns.map(name=>{const v=r[name];const field=config.fields.find(f=>f[0]===name);return <td key={name} className="px-5 py-4 text-slate-600">{field?.[2]==='select'?<Badge tone={tone(v)}>{display(v)}</Badge>:display(v)}</td>})}{(canWrite||canDelete)&&<td className="px-5 py-4"><div className="flex gap-1">{canWrite&&<button onClick={()=>openEdit(r)} className="rounded-lg p-2 text-slate-400 hover:bg-indigo-50 hover:text-indigo-600"><Edit3 size={16}/></button>}{canDelete&&<button onClick={()=>remove(r._id)} className="rounded-lg p-2 text-slate-400 hover:bg-rose-50 hover:text-rose-600"><Trash2 size={16}/></button>}</div></td>}</motion.tr>)}</tbody></table>}</div></Card><Modal open={open} onClose={()=>setOpen(false)} title={`${editing?'Edit':'Add'} ${config.singular}`} wide><form onSubmit={save} className="grid gap-4 sm:grid-cols-2">{config.fields.map(f=><Field key={f[0]} field={f} value={form[f[0]]} options={options} onChange={v=>setForm({...form,[f[0]]:v})}/>)}<div className="flex justify-end gap-2 sm:col-span-2"><Button type="button" variant="secondary" onClick={()=>setOpen(false)}>Cancel</Button><Button type="submit">{editing?'Save changes':'Create'}</Button></div></form></Modal></div>
}
