import { useEffect, useState } from 'react'
import { motion } from 'framer-motion'
import { ArrowUpRight, BookOpen, CircleDollarSign, GraduationCap, Receipt, Users } from 'lucide-react'
import { Link } from 'react-router-dom'
import api, { getError } from '../services/api'
import { Card, Badge } from '../components/ui'
import { useAuth } from '../context/AuthContext'

const cards=[['students','Students',GraduationCap,'/students'],['courses','Active courses',BookOpen,'/courses'],['enrollments','Active enrollments',Users,'/enrollments'],['pendingInvoices','Pending invoices',Receipt,'/invoices']]
export default function Dashboard(){const {user}=useAuth();const [summary,setSummary]=useState(null);const [error,setError]=useState('');useEffect(()=>{api.get('/dashboard/summary').then(r=>setSummary(r.data.summary)).catch(e=>setError(getError(e)))},[]);return <div className="space-y-6"><div><p className="text-sm font-semibold text-indigo-600">Overview</p><h1 className="mt-1 text-2xl font-black tracking-tight text-slate-900 md:text-3xl">Good morning, {user.name.split(' ')[0]}.</h1><p className="mt-1 text-sm text-slate-500">Live data from your LMS backend.</p></div>{error&&<Card className="p-4 text-sm text-rose-600">{error}</Card>}<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([key,label,Icon,to],i)=><motion.div key={key} initial={{opacity:0,y:15}} animate={{opacity:1,y:0}} transition={{delay:i*.06}}><Link to={user.role==='student'&&key==='students'?'/':to}><Card className="group p-5 transition hover:-translate-y-1 hover:shadow-lg"><div className="flex items-start justify-between"><div className="grid size-11 place-items-center rounded-xl bg-indigo-50 text-indigo-600"><Icon size={21}/></div><ArrowUpRight size={18} className="text-slate-300 transition group-hover:text-indigo-500"/></div><div className="mt-5 text-3xl font-black text-slate-900">{summary?.[key]??'—'}</div><div className="mt-1 text-sm text-slate-500">{label}</div></Card></Link></motion.div>)}</div><div className="grid gap-6 xl:grid-cols-[1.4fr_.6fr]"><Card className="p-6"><div className="mb-5 flex items-center justify-between"><div><h2 className="font-bold text-slate-900">System status</h2><p className="text-sm text-slate-500">API summary endpoint</p></div><Badge tone="green">Connected</Badge></div><div className="grid gap-3 sm:grid-cols-3"><div className="rounded-xl bg-slate-50 p-4"><p className="text-xs text-slate-400">Approved / paid</p><p className="mt-1 text-xl font-bold">{summary?.approvedInvoices??'—'}</p></div><div className="rounded-xl bg-slate-50 p-4"><p className="text-xs text-slate-400">Unread approvals</p><p className="mt-1 text-xl font-bold">{summary?.unreadApprovals??'—'}</p></div><div className="rounded-xl bg-slate-50 p-4"><p className="text-xs text-slate-400">Your role</p><p className="mt-1 text-xl font-bold capitalize">{user.role}</p></div></div></Card><Card className="p-6"><CircleDollarSign className="text-indigo-600"/><h2 className="mt-4 font-bold text-slate-900">Quick actions</h2><div className="mt-4 space-y-2">{user.role!=='student'&&<Link className="block rounded-xl bg-indigo-50 px-4 py-3 text-sm font-semibold text-indigo-700" to="/students">Manage students</Link>}<Link className="block rounded-xl bg-slate-50 px-4 py-3 text-sm font-semibold text-slate-700" to="/courses">Browse courses</Link><Link className="block rounded-xl bg-slate-50 px-4 py-3 text-sm font-semibold text-slate-700" to="/notifications">View notifications</Link></div></Card></div></div>}
