import { useState } from 'react'
import { motion } from 'framer-motion'
import { Eye, EyeOff, GraduationCap, LockKeyhole, Mail } from 'lucide-react'
import { Link, useLocation, useNavigate } from 'react-router-dom'
import { useAuth } from '../context/AuthContext'
import { Button, Input } from '../components/ui'
import { getError } from '../services/api'

export default function Login(){
  const {login}=useAuth(); const nav=useNavigate(); const loc=useLocation()
  const [form,setForm]=useState({email:'',password:''}); const [show,setShow]=useState(false); const [error,setError]=useState(''); const [loading,setLoading]=useState(false)
  const submit=async e=>{e.preventDefault();setError('');setLoading(true);try{await login(form.email,form.password);nav(loc.state?.from||'/')}catch(err){setError(getError(err))}finally{setLoading(false)}}
  return <div className="min-h-screen overflow-hidden bg-slate-950"><div className="mx-auto grid min-h-screen max-w-7xl lg:grid-cols-2"><div className="relative hidden overflow-hidden p-12 lg:flex lg:flex-col lg:justify-between"><div className="absolute -left-24 -top-24 size-96 rounded-full bg-indigo-600/30 blur-3xl"/><div className="absolute -bottom-24 -right-24 size-96 rounded-full bg-cyan-500/20 blur-3xl"/><div className="relative flex items-center gap-3 text-white"><div className="grid size-11 place-items-center rounded-2xl bg-white/10"><GraduationCap/></div><b className="text-xl">LMS Portal</b></div><div className="relative max-w-xl"><motion.div initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} transition={{duration:.5}}><p className="mb-4 text-sm font-semibold uppercase tracking-[.25em] text-indigo-300">Learning management system</p><h1 className="text-5xl font-black leading-tight text-white">Manage learning.<br/><span className="text-indigo-300">Move students forward.</span></h1><p className="mt-6 max-w-lg text-slate-300">Students, teachers, courses, attendance, grades, invoices and notifications in one workspace.</p></motion.div></div><p className="relative text-xs text-slate-500">Connected to your Node.js + Express + MongoDB backend.</p></div><div className="flex items-center justify-center bg-slate-50 p-6"><motion.form initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} onSubmit={submit} className="w-full max-w-md"><div className="mb-8 lg:hidden"><div className="mb-5 grid size-12 place-items-center rounded-2xl bg-indigo-600 text-white"><GraduationCap/></div><h1 className="text-3xl font-black text-slate-900">Welcome back</h1></div><div className="mb-8 hidden lg:block"><h2 className="text-3xl font-black text-slate-900">Welcome back</h2><p className="mt-2 text-sm text-slate-500">Sign in to your LMS workspace.</p></div>{error&&<div className="mb-5 rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm text-rose-600">{error}</div>}<div className="space-y-5"><div className="relative"><Input label="Email" type="email" required value={form.email} onChange={e=>setForm({...form,email:e.target.value})} placeholder="you@example.com"/><Mail size={17} className="pointer-events-none absolute right-3 top-9 text-slate-400"/></div><div className="relative"><Input label="Password" type={show?'text':'password'} required value={form.password} onChange={e=>setForm({...form,password:e.target.value})} placeholder="••••••••"/><button type="button" onClick={()=>setShow(v=>!v)} className="absolute right-3 top-9 text-slate-400">{show?<EyeOff size={17}/>:<Eye size={17}/>}</button><LockKeyhole size={17} className="pointer-events-none absolute left-3 top-9 hidden"/></div><Button loading={loading} className="w-full py-3">Sign in</Button><div className="pt-1 text-center text-sm text-slate-500">New student? <Link to="/register" className="font-semibold text-indigo-600 hover:underline">Register</Link></div></div></motion.form></div></div></div>
}
