const r = require("express").Router();
const { protect, authorize } = require("../middleware/authMiddleware");
const Model = require("../models/Grade");
const c = require("../controllers/genericController");
r.use(protect);
r.get("/", c.list(Model, "student assignment course", { studentField: "student" }));
r.post("/", authorize("admin", "staff", "teacher"), c.create(Model));
r.patch("/:id", authorize("admin", "staff", "teacher"), c.update(Model));
r.delete("/:id", authorize("admin", "staff"), c.remove(Model));
module.exports = r;
